theme: minima

collections:
  projects:
    output: true
  experience:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "things"
  - scope:
      path: ""
      type: "experience"
    values:
      layout: "things"
  - scope:
      path: ""
    values:
      layout: "default"